### PR TITLE
Standardizing changelog format across ManageIQ

### PR DESCRIPTION
**Pull request by JPrause**

### CODE REVIEW

**Comment by chrisarcand** [comment]
?

**Comment by JPrause** [comment]
@chrisarcand I'm trying to have all of our repos have a CHANGELOG.md
The vast majority do not,..but I'm working on it.
I'm also trying to standardize all changelogs for the following:
- changleogs to be named: CHANGELOG..md
- contain header and description
- follow the format used in the manageiq repo. If there is any pertinent merges each sprint the changelog will be updated.
- automate as much as is possible.

So in this case, I renamed to CHANGELOG.md and added the header info.
Does this answer the "?"

**Comment by chrisarcand** [comment]
Sure! I was more confused as to why this was opened on our fork of an abandoned project that doesn't actually appear to have any commits from us in it anyway. Not sure why this repo exists at all.

**Comment by JPrause** [comment]
@chrisarcand ha,..gotcha. Yeah we have a lot of repos,..it can be hard to know if any are stale, so I'm blowing through all of them. Let me send an e-mail to the team so others know this as well. Thank you sir!

**Comment by JPrause** [comment]
@miq-bot add_label documentation

**Comment by JPrause** [comment]
Not needed at this time.

**Pull request closed without merging**
